-- Canonical Seedance provider contract (enforced by the service/repository layer):
-- model: doubao-seedance-2-0-260128
-- endpoint: https://ark.cn-beijing.volces.com/api/v3
--
-- This migration intentionally performs no historical rewrite and adds no unique
-- constraint. Existing rows remain untouched; create/update validation prevents
-- new duplicate canonical providers within the same employee group.
