<template>
  <AppLayout><div class="space-y-6">
    <header class="flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-2xl font-semibold text-gray-900 dark:text-white">{{ copy.title }}</h1><p class="mt-1 text-sm text-gray-500">{{ copy.description }}</p></div><button class="btn btn-secondary" @click="load">{{ copy.refresh }}</button></header>
    <section class="card p-5"><h2 class="text-base font-semibold">{{ editingId ? copy.edit : copy.add }}</h2><form class="mt-4 grid gap-3 md:grid-cols-2" @submit.prevent="save"><input v-model="form.display_name" class="input" required :placeholder="copy.channelName" /><select v-model.number="form.group_id" class="input" required><option :value="0">{{ copy.group }}</option><option v-for="g in groups" :key="g.id" :value="g.id">{{ g.name }}</option></select><input v-model="form.api_key" class="input" type="password" autocomplete="new-password" :required="!editingId" :placeholder="editingId ? copy.secretKeep : copy.secret" /><input v-model="form.default_model" class="input" placeholder="Seedance model" /><label class="flex items-center gap-2 text-sm"><input v-model="form.enabled" type="checkbox" />{{ copy.enableNow }}</label><div class="flex gap-2"><button class="btn btn-primary" :disabled="saving">{{ copy.save }}</button><button v-if="editingId" type="button" class="btn btn-secondary" @click="resetForm">{{ copy.cancel }}</button></div></form></section>
    <section class="grid gap-4 xl:grid-cols-2"><article v-for="p in providers" :key="p.id" class="card p-5"><div class="flex items-start justify-between gap-3"><div><h2 class="font-semibold text-gray-900 dark:text-white">{{ p.display_name }}</h2><p class="text-sm text-gray-500">{{ p.group_name }} / {{ p.default_model || 'model missing' }}</p></div><span class="text-sm">{{ p.enabled ? 'enabled' : 'disabled' }}</span></div><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-gray-500">Secret</dt><dd>{{ p.masked_key || 'not configured' }}</dd></div><div><dt class="text-gray-500">tiny_real</dt><dd>{{ authLabel(p) }}</dd></div></dl><div class="mt-4 flex flex-wrap gap-2"><button class="btn btn-secondary" @click="startEdit(p)">{{ copy.edit }}</button><button class="btn btn-secondary" @click="toggle(p)">{{ p.enabled ? 'Disable' : 'Enable' }}</button><button class="btn btn-primary" :disabled="!p.enabled || !p.api_key_configured || !!p.tiny_real_authorized_at" @click="authorize(p)">Grant one tiny_real</button></div></article><p v-if="!providers.length" class="text-sm text-gray-500">No channel yet. Complete the binding above.</p></section>
  </div></AppLayout>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import AppLayout from '@/components/layout/AppLayout.vue'
import { adminAPI } from '@/api/admin'
import type { VideoProviderAccount } from '@/api/admin/video'
import { useAppStore } from '@/stores'
import { extractApiErrorMessage } from '@/utils/apiError'
const app = useAppStore()
const copy = { title: '\u0053\u0065\u0065\u0064\u0061\u006e\u0063\u0065 \u89c6\u9891\u901a\u9053', description: '\u5148\u7ed1\u5b9a\u5458\u5de5\u5206\u7ec4\u4e0e\u5bc6\u94a5\uff0c\u518d\u542f\u7528\u901a\u9053\u3002tiny_real \u662f\u4e00\u6b21\u6027\u4ed8\u8d39\u95e8\u7981\uff0c\u672c\u9875\u4e0d\u4f1a\u81ea\u52a8\u51fa\u7247\u3002', refresh: '\u5237\u65b0', add: '\u65b0\u589e\u901a\u9053', edit: '\u7f16\u8f91\u901a\u9053', cancel: '\u53d6\u6d88', channelName: '\u901a\u9053\u540d\u79f0', group: '\u9009\u62e9\u5458\u5de5\u5206\u7ec4', secret: '\u4e0a\u6e38\u5bc6\u94a5\uff08\u4fdd\u5b58\u540e\u4ec5\u663e\u793a\u63a9\u7801\uff09', secretKeep: '\u65b0\u5bc6\u94a5\uff08\u7559\u7a7a\u5219\u4fdd\u7559\u539f\u5bc6\u94a5\uff09', enableNow: '\u7acb\u5373\u542f\u7528', save: '\u4fdd\u5b58\u901a\u9053' }
const providers = ref<VideoProviderAccount[]>([])
const groups = ref<Array<{ id: number; name: string }>>([])
const saving = ref(false)
const editingId = ref<number | null>(null)
const form = reactive({ group_id: 0, display_name: 'Seedance 2.0', api_key: '', default_model: 'doubao-seedance-2-0-pro', enabled: false })
async function load() { try { providers.value = (await adminAPI.video.listProviders()).items; groups.value = await adminAPI.groups.getAll() } catch (error) { app.showError(extractApiErrorMessage(error, 'Failed to load video channels')) } }
function resetForm() { editingId.value = null; Object.assign(form, { group_id: 0, display_name: 'Seedance 2.0', api_key: '', default_model: 'doubao-seedance-2-0-pro', enabled: false }) }
function startEdit(provider: VideoProviderAccount) { editingId.value = provider.id; Object.assign(form, { group_id: provider.group_id, display_name: provider.display_name, api_key: '', default_model: provider.default_model, enabled: provider.enabled }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
async function save() { saving.value = true; try { if (editingId.value) { const payload = { group_id: form.group_id, display_name: form.display_name, default_model: form.default_model, enabled: form.enabled, ...(form.api_key ? { api_key: form.api_key } : {}) }; await adminAPI.video.updateProvider(editingId.value, payload) } else { await adminAPI.video.createProvider({ ...form, provider: 'seedance' }) }; resetForm(); app.showSuccess('Channel saved'); await load() } catch (error) { app.showError(extractApiErrorMessage(error, 'Save failed')) } finally { saving.value = false } }
async function toggle(provider: VideoProviderAccount) { try { await adminAPI.video.updateProvider(provider.id, { enabled: !provider.enabled }); await load() } catch (error) { app.showError(extractApiErrorMessage(error, 'Update failed')) } }
async function authorize(provider: VideoProviderAccount) { if (!window.confirm('Grant this channel one tiny_real authorization? This does not dispatch.')) return; try { await adminAPI.video.authorizeTinyReal(provider.id); app.showSuccess('One-time authorization recorded'); await load() } catch (error) { app.showError(extractApiErrorMessage(error, 'Authorization failed')) } }
const authLabel = (provider: VideoProviderAccount) => provider.tiny_real_consumed_at ? 'consumed' : provider.tiny_real_authorized_at ? 'authorized, pending' : 'not authorized'
onMounted(load)
</script>
