<template><AppLayout><div class="space-y-5"><header><h1 class="text-2xl font-semibold text-gray-900 dark:text-white">{{ copy.title }}</h1><p class="mt-1 text-sm text-gray-500">{{ copy.description }}</p></header><div class="flex gap-3"><select v-model="status" class="input max-w-52" @change="load"><option value="">{{ copy.all }}</option><option v-for="item in states" :key="item">{{ item }}</option></select><button class="btn btn-secondary" @click="load">{{ copy.refresh }}</button></div><div class="card overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th class="p-3">Task ID</th><th class="p-3">Upstream task ID</th><th class="p-3">{{ copy.state }}</th><th class="p-3">{{ copy.cost }}</th><th class="p-3">Dispatch</th><th class="p-3">{{ copy.asset }}</th></tr></thead><tbody><tr v-for="task in tasks" :key="task.id"><td class="p-3"><RouterLink class="text-primary-600" :to="`/admin/video/tasks/${task.id}`">#{{ task.id }}</RouterLink><div class="max-w-56 truncate text-xs text-gray-500">{{ task.prompt }}</div></td><td class="p-3 font-mono text-xs">{{ task.upstream_task_id || '-' }}</td><td class="p-3">{{ task.status }}</td><td class="p-3">{{ task.cost_amount }} {{ task.currency || 'USD' }}</td><td class="p-3">{{ task.real_dispatch_count }}</td><td class="p-3"><a v-if="task.result_url" :href="task.result_url" target="_blank" rel="noreferrer" class="text-primary-600">{{ copy.open }}</a><span v-else class="text-red-600">{{ task.error_message || task.provider_error_message || '-' }}</span></td></tr></tbody></table><p v-if="!tasks.length" class="p-6 text-center text-sm text-gray-500">{{ copy.empty }}</p></div></div></AppLayout></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import AppLayout from '@/components/layout/AppLayout.vue'
import { adminAPI } from '@/api/admin'
import type { VideoTaskAdmin } from '@/api/admin/video'
import { useAppStore } from '@/stores'
import { extractApiErrorMessage } from '@/utils/apiError'
const app = useAppStore(); const tasks = ref<VideoTaskAdmin[]>([]); const status = ref(''); const states = ['queued', 'submitted', 'running', 'succeeded', 'failed', 'cancelled']
const copy = { title: '\u89c6\u9891\u4efb\u52a1\u8bc1\u636e', description: '\u6838\u5bf9\u672c\u5730\u4efb\u52a1\u3001\u4e0a\u6e38 task id\u3001\u7ec8\u6001\u3001\u8d44\u4ea7\u3001\u8d39\u7528\u4e0e\u771f\u5b9e dispatch \u6b21\u6570\u3002', all: '\u5168\u90e8\u72b6\u6001', refresh: '\u5237\u65b0', state: '\u72b6\u6001', cost: '\u8d39\u7528', asset: '\u8d44\u4ea7\u6216\u9519\u8bef', open: '\u67e5\u770b\u8d44\u4ea7', empty: '\u6682\u65e0\u4efb\u52a1\u8bc1\u636e\u3002' }
async function load() { try { tasks.value = (await adminAPI.video.listTasks(1, 100, status.value)).items } catch (error) { app.showError(extractApiErrorMessage(error, 'Failed to load tasks')) } }
onMounted(load)
</script>
