CREATE TABLE IF NOT EXISTS api_keys (id BIGSERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS users    (id BIGSERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS groups   (id BIGSERIAL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS accounts (id BIGSERIAL PRIMARY KEY);
